// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuvTqF0xlkJrFlOW3EZWzE1-UEzIioV0s',
    appId: '1:310305465296:web:2f02d7fcac683f63384fd5',
    messagingSenderId: '310305465296',
    projectId: 'flutterbasicemailauth',
    authDomain: 'flutterbasicemailauth.firebaseapp.com',
    storageBucket: 'flutterbasicemailauth.appspot.com',
    measurementId: 'G-WHGBQCHM32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKFHjDzf42WkNXJaLPWB2xe1fC_ps9-hU',
    appId: '1:310305465296:android:1ddc1dcd0731b300384fd5',
    messagingSenderId: '310305465296',
    projectId: 'flutterbasicemailauth',
    storageBucket: 'flutterbasicemailauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRvxSyHwgK9c1W42evLtqLGj_AZg7Mp6I',
    appId: '1:310305465296:ios:347d090fa9458c6e384fd5',
    messagingSenderId: '310305465296',
    projectId: 'flutterbasicemailauth',
    storageBucket: 'flutterbasicemailauth.appspot.com',
    iosClientId: '310305465296-669uovtcqepupdjbm6gts2n9r309prmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterbasicapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRvxSyHwgK9c1W42evLtqLGj_AZg7Mp6I',
    appId: '1:310305465296:ios:347d090fa9458c6e384fd5',
    messagingSenderId: '310305465296',
    projectId: 'flutterbasicemailauth',
    storageBucket: 'flutterbasicemailauth.appspot.com',
    iosClientId: '310305465296-669uovtcqepupdjbm6gts2n9r309prmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterbasicapp',
  );
}
